import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import SignInSignUp from "@/components/core/SignInSignUp";
import { ThemeProvider } from "@/components/layout/theme-provider";
import NavigationBar from "@/components/layout/NavigationBar";
import ClerkToSupa from "@/components/layout/ClerkToSupa";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Uvibe - Where fashion meets individuality",
  description: "Generated by create next app",
  icons: {
    icon: "/brand/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <SignedIn>
              <ClerkToSupa>
                <div>
                  <NavigationBar />
                </div>
                <div className=" mt-24">{children}</div>
                <Toaster position="top-center" />
              </ClerkToSupa>
            </SignedIn>
            <SignedOut>
              <SignInSignUp />
            </SignedOut>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
